### PR TITLE
Request throttling

### PR DESCRIPTION
**Pull request by danielmkn**
PTRENG-4523, add rate limiting and request throttling on API gateway.
API gateway is the front-service REST API that can be accessed through the public internet, thus rate limiting must be applied.

### CODE REVIEW

**Review by shrajfr12 — DISMISSED** [review]
lgtm

**Review by alexhung — APPROVED** [review]
:shipit:

**Comment by alexhung** [comment]
@danielmkn Actually, can you update `CHANGELOG.md` with the change?

**Review by alexhung — CHANGES_REQUESTED** [review]
Update CHNAGELOG please

**Comment by danielmkn** [comment]
changelog updated

**Review by alexhung — APPROVED** [review]

**Review by alexhung — APPROVED** [review]

**Pull request merged**
